export const LISTA_MOTIVOS_DEBITO: string[] = [
  'Borrar',
  'No aplica',
  'Afiliado capitado',
  'Afiliado dado de baja',
  'Alta demorada criterio auditoria medica',
  'Conteo de medicacion erroneo hojas de enfermeria no identificadas con fecha',
  'Coseguro no cobrado',
  'Debito 20% urgencia modulos',
  'Debito 20% urgencia prestaciones',
  'Debito por diferencia en la inclusiones modulares',
  'Debito por falta de historia clinica',
  'Debito por historias clinicas de distintos pacientes en la misma internacion',
  'Debito por normas contractuales (ejemplo veda+vcc)',
  'Debito por normas operativas',
  'Debito segun normas del nomenclador',
  'Débitos varios, recibido fuera de término por Tesorería, emisión de nc condicional al cobro de la factura',
  'Demora en Inter Consulta',
  'Demora en resolución quirúrgica',
  'Diagnostico ilegible',
  'Diagnostico no reconocido',
  'Diferencia de aranceles',
  'Diferencia de coseguro',
  'Diferencia de criterio medico/prestaciones no justificadas',
  'Diferencia de valor en medicamentos/descartables',
  'Documentacion adulterada',
  'Ecografia de partes blandas incluida en ecografia abdominal',
  'Ecografia renal incluida en abdominal',
  'El valor de los impuestos a abonar en el proceso de la refactura superan el importe a refacturar',
  'Error de carga (codigos-inclusiones)',
  'Error de Open',
  'Error en el cálculo de porcentaje de códigos múltiples',
  'Exceso de facturacion en medicamentos y descartables',
  'Facturacion duplicada',
  'Facturado a financiador incorrecto',
  'Facturado con nota de departamento comercial',
  'Falta de autorizacion',
  'Falta de documentacion avalatoria',
  'Falta de historia/informe.',
  'Falta de troqueles-stickers de medicacion o materiales',
  'Falta firma paciente',
  'Falta firma profesional',
  'Falta informe',
  'Historia clinica incompleta',
  'Honorarios profesionales pagados en forma directa',
  'Incluido en APB',
  'Iva mal facturado',
  'Material/ Medicamentos provistos por O.S.',
  'Material no utilizado',
  'Medicación no suministrada',
  'No indicado',
  'No reconoce prestación',
  'Orden sin diagnóstico',
  'Prestacion fuera de termino',
  'Prestacion incluida en otra',
  'Prestacion incluida en otra liquidacion',
  'Prestacion no homologada',
  'Prestacion no justificada',
  'Prestacion sin convenio',
  'Presupuesto facturado con nota no reconocido',
  'Presupuesto rechazado y facturados con indicacion comercial',
  'Rechazo de refactura por mantener motivos de debitos originales',
  'Supera tope anual'
];

export const LISTA_MOTIVOS_REFACTURA: string[] = [
  'Borrar', 'No aplica', 'Casos: Afiliados activos.', 'Casos: Discrepancia cobertura pensión.',
  'Casos: Excepciones refacturadas.', 'Casos: Médico externo sin historia clínica.',
  'Corrección de error de Open', 'Débitos Inválidos: Aplicados erróneamente.',
  'Doc. y Aut.: Autorización recibida posterior al cierre.', 'Doc. y Aut.: Autorización vigente.',
  'Doc. y Aut.: Doc. completa enviada.', 'Doc. y Aut.: Facturado en tiempo.',
  'Doc. y Aut.: Info. filiatoria completa.', 'Doc. y Aut.: Justificado en historia clínica.',
  'Doc. y Aut.: Orden con diagnóstico, se aclara con historia clínica',
  'Doc. y Aut.: Se envía documentación omitida', 'Doc. y Aut.: Se envía troquel/sticker',
  'Doc. y Aut.: Según normas vigentes.', 'Excepciones: Bonificación medicación.',
  'Excepciones: Bonificación prestación.', 'Excepciones: Reclamos/comerciales.',
  'Gestión: Aclaración procedimiento.', 'Gestión: Afiliado dado de baja.',
  'Gestión: Ajustes en coseguro.', 'Gestión: Ajuste por presupuesto.',
  'Gestión: Aplicación incorrecta de IVA.', 'Gestión: Consumos correctos.',
  'Gestión: Corrección facturación módulos.', 'Gestión: Financidor demoró respuesta.',
  'Gestión: Medicamentos mal facturados.', 'Gestión Méd.: Aclaración de diagnóstico',
  'Gestión Méd.: Ajuste fechas derivación.', 'Gestión Méd.: Criterio en diagnósticos.',
  'Gestión Méd.: Historia clínica firmada.', 'Gestión Méd.: Normas sanatoriales.',
  'Gestión Méd.: Postoperatorios/antibióticos.', 'Gestión Méd.: Tratamientos infecciones.',
  'Gestión Méd.: Tratamientos médicos.', 'Gestión Méd.: Urgencia sin consentimiento.',
  'Normas: Adjunta norma del Nom. Nac.', 'Normas: Ajustes valores medicación/material.',
  'Normas: Aplicación de normas acordadas.', 'Normas: Aranceles vigentes Colegio Bioquím.',
  'Normas: Cambios deben ser acordados.', 'Normas: Exclusión no explícita.',
  'Normas: Facturación según módulos vigentes.', 'Normas: Inclusión/Exclusión según acuerdo.',
  'Normas: Incompatibilidad normativa.', 'Normas: Obligación de cobertura por ley',
  'Normas: Prestación arancel convenido.', 'Normas: Prestación no respondida por financ.',
  'Normas: Prestación según presupuesto.', 'Normas: Recargos urgencia según Nac. Nom.',
  'Normas: Refacturación por IVA.', 'Normas: Valores de contrastes vigentes.',
  'Normas: Valores medicación/material convenio.', 'Prestaciones: Aranceles según CEDIM.',
  'Prestaciones: Consultas previas/post-proced.', 'Prestaciones: Homologada.',
  'Prestaciones: Inclusión incorrecta.', 'Prestaciones: No incluidas según Nom. Nac.',
  'Prestaciones: Material no incluido en base.', 'Prestaciones: Procedimientos ampliados.',
  'Prestaciones: Relacionadas a prestación.'
];
