spring.application.name=backend

# ===============================
# CONEXIÓN A POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/Debitos
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===============================
# Imprime las consultas SQL en la consola (ideal para ver qué hace por detrás)
spring.jpa.show-sql=true

# CRÍTICO: Como ya tenés la base de datos creada de tu app en C#,
# usamos "none" para que Spring Boot NO intente borrar, recrear o alterar tus tablas automáticamente.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONFIGURACIÓN DE BATCH (RENDIMIENTO)
# ===============================
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true