# src/main/resources/application-prod.properties
spring.datasource.url=jdbc:postgresql://debitos-auditoria.cmm.com.ar:5432/debitos_prod
spring.datasource.username=usr_debitos
spring.datasource.password=password_seguro_123
spring.jpa.hibernate.ddl-auto=validate

# Prevención de Time-outs y Gestión de Conexiones (HikariCP)
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=15000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.leak-detection-threshold=10000
