# src/main/resources/application-prod.properties
spring.datasource.url=jdbc:postgresql://debitos-auditoria.cmm.com.ar:5432/debitos_prod
spring.datasource.username=usr_debitos
spring.datasource.password=password_seguro_123
spring.jpa.hibernate.ddl-auto=update